### ISSUE TITLE
GenerateHTMLPage function 

### ISSUE THREAD

**Issue by hphan9** [dbelokon/glazed-donut#3]
There is a small bug in the GenerateHTMLPage function.
When transforming the text,": every blank line should be considered a paragraph limit and the text transformed into ```<p>...</p>```.
In this function, you put \n after ```<p> <\p>``` and inside the paragraph, you replace "\n" with ```<br/>``` . "\n" should be replaced with white space.
Code:  ``` htmlBody += $"<p>{p.Replace("\n", "<br/>")}</p>\n";```

**Comment by dbelokon** [comment]
Fixed!

I thought the new line found in the text file had to be preserved, instead of letting the browser decide.
